### ISSUE TITLE
Create in-game assets

### ISSUE THREAD

**Issue by GlennKintscher** [KatastrophenTeam/BreaktimeSnack#1]
**How to get them:**
1. Go to Smashboards.com
2. find Thread containing the Characters Framedata
3. Save existing Attacks
4. include Textdocument containing Source for Permission asking

**Remarks:**
- names of the files: nameOfCharacter_NameOfAttack
- file type: .GIF

**Characters:**
- [x] Bowser
- [x] Captain Falcon
- [x] Donkey Kong
- [x] Dr. Mario
- [x] Falco
- [x] Fox
- [x] Ganondorf
- [x] Ice Climbers
- [x] Jigglypuff
- [x] Kirby
- [x] Link
- [x] Luigi
- [x] Mario
- [x] Marth
- [x] Mewtwo
- [x] Mr. Game & Watch
- [x] Ness
- [x] Sheik
- [x] Peach
- [x] Pichu
- [x] Pikachu
- [x] Roy
- [x] Samus
- [x] Yoshi
- [x] Young Link
- [x] Zelda

**Comment by BodooKing** [comment]
Assets found in SSBM.rar #25

**Comment by GlennKintscher** [comment]
Two small fixes:
- `./assets/pikachu/pikachu_attacks__strong_pika-kick-low.gif` renamed to `./assets/pikachu/pikachu_attacks_strong_pika-kick-low.gif`
- `./assets/pikachu/desktop.ini` removed

Download @ https://ufile.io/8bt3f (valid: 30 days)
