### ISSUE TITLE
Create Character Textfiles

### ISSUE THREAD

**Issue by BodooKing** [KatastrophenTeam/BreaktimeSnack#2]
Create Textfiles named after the Characters containing:

1. Their Descriptions based on the Trophies (including the Throphys Name and Number)
2. Their Attacks with its Name and Inputcombination

There are 7 Types of Attacks:

- Standing
- Jumping Attacks
- Strong Attacks
- Smash Attacks
- Special Attacks
- Throws
- Taunt

Format:
[Category A]
//Subcategory B
Object 1
Object 2
{Attachment C to B}
Attachment 3 to 1
Attachment 4 to 2

Characters:

- [x] Bowser
- [x] Captain Falcon
- [x] Donkey Kong
- [x] Dr. Mario
- [x] Falco
- [x] Fox
- [x] Ganondorf
- [x] Ice Climbers
- [x] Jigglypuff
- [x] Kirby
- [x] Link
- [x] Luigi
- [x] Marth
- [x] Mewtwo
- [x] Mr. Game & Watch
- [x] Ness
- [x] Sheik
- [x] Peach
- [x] Pichu
- [x] Pikachu
- [x] Roy
- [x] Samus
- [x] Yoshi
- [x] Young Link
- [x] Zelda

**Comment by BodooKing** [comment]
[Donkey Kong.txt](https://github.com/KatastrophenTeam/BreaktimeSnack/files/903423/Donkey.Kong.txt)
[Dr. Mario.txt](https://github.com/KatastrophenTeam/BreaktimeSnack/files/903425/Dr.Mario.txt)
[Falco.txt](https://github.com/KatastrophenTeam/BreaktimeSnack/files/903424/Falco.txt)
[Fox.txt](https://github.com/KatastrophenTeam/BreaktimeSnack/files/903426/Fox.txt)
[Ganondorf.txt](https://github.com/KatastrophenTeam/BreaktimeSnack/files/903429/Ganondorf.txt)
[Ice Climbers.txt](https://github.com/KatastrophenTeam/BreaktimeSnack/files/903428/Ice.Climbers.txt)
[Jigglypuff.txt](https://github.com/KatastrophenTeam/BreaktimeSnack/files/903427/Jigglypuff.txt)
[Kirby.txt](https://github.com/KatastrophenTeam/BreaktimeSnack/files/903430/Kirby.txt)
[Link.txt](https://github.com/KatastrophenTeam/BreaktimeSnack/files/903431/Link.txt)
[Uploading Luigi.txt…]()
[Uploading Mario.txt…]()
[Uploading Marth.txt…]()
[Uploading Mewtwo.txt…]()
[Uploading Mr. Game & Watch.txt…]()
[Uploading Ness.txt…]()
[Uploading Peach.txt…]()
[Uploading Pichu.txt…]()
[Uploading Pikachu.txt…]()
[Uploading Roy.txt…]()
[Uploading Samus.txt…]()
[Uploading Sheik.txt…]()
[Uploading Yoshi.txt…]()
[Uploading Young Link.txt…]()
[Uploading Zelda.txt…]()
[Uploading Bowser.txt…]()
[Uploading Captain Falcon.txt…]()

**Comment by GlennKintscher** [comment]
What's about [JSON](https://de.wikipedia.org/wiki/JavaScript_Object_Notation)?

**Comment by GlennKintscher** [comment]
Waiting for #6

**Comment by GlennKintscher** [comment]
In Review

**Comment by GlennKintscher** [comment]
Done
