### ISSUE TITLE
Wrap Up YAML-Characterfiles

### ISSUE THREAD

**Issue by BodooKing** [KatastrophenTeam/BreaktimeSnack#25]
To finish up the YAML Data there are the following Steps:

1. Check for Mistakes (Done by Reviewing the existing YAML)
2. Add Tier to the Character
3. Add Dodge Category
4. Delete all Infos not to be found in Animations (Except: Trophy, Tier; Taunt still to be made)

Process:
- [x] Bowser
- [x] Captain Falcon
- [x] Donkey Kong
- [x] Dr. Mario
- [x] Falco
- [x] Fox
- [x] Ganondorf
- [x] Ice Climbers
- [x] Jigglypuff
- [x] Kirby
- [x] Link
- [x] Luigi
- [x] Mario
- [x] Marth
- [x] Mewtwo
- [x] Mr. Game & Watch
- [x] Ness
- [x] Peach
- [x] Pichu
- [x] Pikachu
- [x] Roy
- [x] Samus
- [x] Sheik
- [x] Yoshi
- [x] Young Link
- [x] Zelda

**Comment by BodooKing** [comment]
https://drive.google.com/open?id=0By0hHdJIDINiTktKUWxpNFIwS1E

**Comment by GlennKintscher** [comment]
Fixed some errors
[characters.zip](https://github.com/KatastrophenTeam/BreaktimeSnack/files/961107/characters.zip)
